# Generated by Django 5.0.7 on 2024-07-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='website',
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.resume'),
        ),
    ]
